server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**, /auth
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**, /products
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**, /orders
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**, /cart
        - id: category-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/categories/**, /categories
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/reviews/**, /reviews

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
